language: R
cache: packages

install:
    - Rscript -e 'install.packages(c("testthat", "dplyr", "dbplyr", "tidyr", "DBI", "RMariaDB", "RSQLite", "yaml", "devtools"), quiet=FALSE)'

script:
    - Rscript -e 'devtools::test(stop_on_failure=TRUE)'

#before_cache: Rscript -e 'remotes::install_cran("pkgdown")'
#deploy:
#  provider: script
#  script: Rscript -e 'pkgdown::deploy_site_github()'
#  skip_cleanup: true