# developed from: https://github.com/r-lib/actions/tree/master/examples#readme

name: test-package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        r-version: [3.5, 3.6]

    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
      - name: Install dependencies
        run: |
          install.packages(c("remotes", "rcmdcheck"))
          install.packages(c("testthat", "dplyr", "dbplyr", "tidyr", "DBI", "RMariaDB", "RSQLite", "yaml", "devtools"), quiet=FALSE)
          remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}
      - name: Check
        run: |
          options(crayon.enabled = TRUE)
          devtools::test(stop_on_failure=TRUE)
        shell: Rscript {0}
